### ISSUE TITLE
A non-exception error occurred running the Kurtosis module executor

### ISSUE THREAD

**Issue by dmitryr117** [kurtosis-tech/near-kurtosis-module#76]
Hello. When I try to run a kurtosis docker image using docker-compose I get this:

```
A non-exception error occurred running the Kurtosis module executor:
Error: An error occurred getting the module container args from the environment
    at KurtosisModuleExecutor.<anonymous> (/run/node_modules/kurtosis-module-api-lib/build/lib/execution/kurtosis_module_executor.js:60:68)
    at step (/run/node_modules/kurtosis-module-api-lib/build/lib/execution/kurtosis_module_executor.js:33:23)
    at Object.next (/run/node_modules/kurtosis-module-api-lib/build/lib/execution/kurtosis_module_executor.js:14:53)
    at /run/node_modules/kurtosis-module-api-lib/build/lib/execution/kurtosis_module_executor.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/run/node_modules/kurtosis-module-api-lib/build/lib/execution/kurtosis_module_executor.js:4:12)
    at KurtosisModuleExecutor.run (/run/node_modules/kurtosis-module-api-lib/build/lib/execution/kurtosis_module_executor.js:53:16)
    at Object.<anonymous> (/run/build/main.js:9:10)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```
here is the docker-compose setup:
```
version: '3'

services:
  kurtosis-near:
    image: kurtosistech/near-kurtosis-module:0.5.25
    container_name: kurtosis-near
    restart: on-failure
```
